---
# defaults file for multiflexi_server
multiflexi_server_database_engines:
  - sqlite
  - pgsql
  - mysql
  # - mssql

multiflexi_server_db_type: sqlite  # default database type, can be overridden in playbook or inventory
multiflexi_server_webserver_type: apache  # default web server type, can be overridden in playbook or inventory

# Repository configuration
multiflexi_repository_channel: testing
multiflexi_repositories:
  testing:
    repo_url: http://repo.vitexsoftware.com
    gpg_key: http://repo.vitexsoftware.com/KEY.gpg
  stable:
    repo_url: https://repo.multiflexi.eu
    gpg_key: https://repo.multiflexi.eu/KEY.gpg
