---
- name: Download the VitexSoftware GPG key
  ansible.builtin.get_url:
    url: "{{ multiflexi_repositories[multiflexi_repository_channel].gpg_key }}"
    dest: /usr/share/keyrings/vitexsoftware-archive-keyring.gpg
    mode: "0644"
  become: true

- name: Ensure the gpg binary is installed
  ansible.builtin.apt:
    name: gnupg
    state: present
  become: true

- name: Add VitexSoftware repo for {{ ansible_distribution_release }}
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/vitexsoftware-archive-keyring.gpg] {{ multiflexi_repositories[multiflexi_repository_channel].repo_url }} {{ ansible_distribution_release }} main backports"
    state: present
    filename: vitexsoftware
  become: true
